[tool.poetry]
  authors = ["Paulo V C Medeiros <paulo.medeiros@smhi.se>"]
  description = "A simple package to test OpenAI API capabilities."
  license = "MIT"
  name = "chat_gpt"
  readme = "README.md"
  version = "0.1.0"

[build-system]
  build-backend = "poetry.core.masonry.api"
  requires = ["poetry-core"]

[tool.poetry.scripts]
  chatgpt = "chat_gpt.__main__:main"

[tool.poetry.dependencies]
  # Python version
  python = ">=3.9,<3.9.7 || >3.9.7,<3.13"
  # Deps that should have been openapi deps
  matplotlib = "^3.8.0"
  plotly = "^5.18.0"
  scikit-learn = "^1.3.2"
  scipy = "^1.11.3"
  # Other dependencies
  numpy = "^1.26.1"
  openai = "^0.28.1"
  pandas = "^2.1.2"
  streamlit = "^1.28.0"
  streamlit-chat = "^0.1.1"
  tiktoken = "^0.5.1"

[tool.poetry.group.dev.dependencies]
  black = "^23.10.1"
  flakeheaven = "^3.3.0"
  ipython = "^8.16.1"
  isort = "^5.12.0"
  pydoclint = "^0.3.8"
  pytest = "^7.4.3"
  ruff = "^0.1.3"

  ##################
  # Linter configs #
  ##################

[tool.black]
  line-length = 90

[tool.isort]
  line_length = 90
  profile = "black"
