[tool.poetry]
  authors = ["Paulo V C Medeiros <paulo.medeiros@smhi.se>"]
  description = "A simple package to test OpenAI API capabilities."
  license = "MIT"
  name = "chat_gpt"
  readme = "README.md"
  version = "0.1.0"

[tool.poetry.scripts]
  chatgpt = "chat_gpt.__main__:main"

[tool.poetry.dependencies]
  flask = "^3.0.0"
  flask-bootstrap = "^3.3.7.1"
  openai = "^0.28.1"
  python = "^3.9"

[tool.poetry.group.dev.dependencies]
  black = "^23.10.1"
  flakeheaven = "^3.3.0"
  ipython = "^8.16.1"
  isort = "^5.12.0"
  pydoclint = "^0.3.8"
  pytest = "^7.4.3"
  ruff = "^0.1.3"

[build-system]
  build-backend = "poetry.core.masonry.api"
  requires = ["poetry-core"]
